# Generated by Django 4.0.5 on 2022-06-25 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_remove_room_participant_room_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='participant',
        ),
        migrations.AddField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
